[tool.poetry]
name = "fhir-sheets"
version = "3.0.1"
description = "FhirSheets is a command-line tool that reads an Excel file in FHIR cohort format and generates FHIR bundle JSON files from it. Each row in the template Excel file is used to create an individual JSON file, outputting them to a specified folder."
authors = ["Kate Riley <Kate.Riley@gtri.gatech.edu>"]
packages = [
    {include = "fhir_sheets", from = "src"},
    {include = "langgraph_dev", from = "src"}
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.13,<4.0.0"  # Specify the compatible Python version here
et-xmlfile = "2.0.0"
jsonpath-ng = "1.8.0"
openpyxl = "3.1.5"
orjson = "3.11.9"
ply = "3.11"
pytest = "8.4.2"
pytest_cov = "7.1.0"
langchain-core = "^1.5.4"
langchain-openai = "^1.5.0"
langgraph = "^1.2.11"
python-dotenv = "^1.0.0"

[tool.poetry.scripts]
fhir-sheets = "fhir_sheets.cli.main:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[pytest]
testpaths = ["tests"]